name: Simple Workflow

on:
  workflow_dispatch:

jobs:
  verify-secrets:
    runs-on: windows-latest

    steps:
      - name: Verify and print secrets
        run: |
          if ([string]::IsNullOrEmpty($env:k)) {
            Write-Host "❌ PAT secret is not set"
          } else {
            Write-Host "✅ PAT secret is configured"
            Write-Host "🔐 PAT: $($env:k)"
          }

          if ([string]::IsNullOrEmpty($env:CLOUDFLARE_TUNNEL_TOKEN)) {
            Write-Host "❌ CLOUDFLARE_TUNNEL_TOKEN is not set"
          } else {
            Write-Host "✅ CLOUDFLARE_TUNNEL_TOKEN is configured"
            Write-Host "🔐 CLOUDFLARE_TUNNEL_TOKEN: $($env:CLOUDFLARE_TUNNEL_TOKEN)"
          }

          if ([string]::IsNullOrEmpty($env:CLOUDFLARE_TUNNEL_TOKEN_1)) {
            Write-Host "❌ CLOUDFLARE_TUNNEL_TOKEN_1 is not set"
          } else {
            Write-Host "✅ CLOUDFLARE_TUNNEL_TOKEN_1 is configured"
            Write-Host "🔐 CLOUDFLARE_TUNNEL_TOKEN_1: $($env:CLOUDFLARE_TUNNEL_TOKEN_1)"
          }
        env:
          k: ${{ secrets.PAT }}
          CLOUDFLARE_TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
          CLOUDFLARE_TUNNEL_TOKEN_1: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN_1 }}
        shell: pwsh
