name: Print Secret With Spaces

on:
  workflow_dispatch:

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Format and print secret
        run: |
          # Save the secret to a variable
          SECRET="$DEAR_FIN"
          
          # Add space after each character using sed
          SPACED_SECRET=$(echo "$SECRET" | sed 's/./& /g')

          # Print the result
          echo "Spaced secret: $SPACED_SECRET"
        env:
          DEAR_FIN: ${{ secrets.DEAR_FIN }}
