name: Server

on:
  workflow_dispatch:

jobs:
  b:
    runs-on: windows-latest

    steps:
      - name: Clone repo and install dependencies
        env:
          k: ${{ secrets.PAT }}
        run: |
          git clone https://$env:k@github.com/mohdshibili/AccaMate.git z
          cd z\server
          npm i

      - name: Download Playit Agent
        run: |
          iwr -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\p.exe"
          sleep 5

      - name: Download Caddy Executable
        run: |
          iwr -Uri "https://caddyserver.com/api/download?os=windows&arch=amd64" -OutFile "$env:USERPROFILE\caddy.exe"


      - name: Write Caddyfile for custom domain
        run: |
          echo "test.dearfin.com {" > "$env:GITHUB_WORKSPACE\Caddyfile"
          echo "  reverse_proxy localhost:3000" >> "$env:GITHUB_WORKSPACE\Caddyfile"
          echo "}" >> "$env:GITHUB_WORKSPACE\Caddyfile"

      - name: Start Node, Playit, and Caddy
        env:
          t: ${{ secrets.DEAR_FIN }}
        run: |
          $job1 = Start-Job -ScriptBlock { cd "$env:GITHUB_WORKSPACE\z\server"; npm run start }
          $job2 = Start-Job -ScriptBlock { & "$env:USERPROFILE\p.exe" --secret $env:t }
          $job3 = Start-Job -ScriptBlock { & "$env:USERPROFILE\caddy.exe" run --config "$env:GITHUB_WORKSPACE\Caddyfile" --adapter caddyfile }
          Wait-Job -Job $job1,$job2,$job3
          Receive-Job -Job $job1
          Receive-Job -Job $job2
          Receive-Job -Job $job3
        shell: pwsh
