name: Node.js Server with Playit.gg

on:
  workflow_dispatch:

jobs:
  node-server:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Download and Install Playit.gg
        run: |
          Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
          Start-Sleep -Seconds 5  # Allow the download to complete

      - name: Start Node.js server and Playit.gg tunnel concurrently
        env:
          PLAYIT_AUTH_KEY: ${{ secrets.PLAYIT_AUTH_KEY }}
        run: |
          $nodeJob = Start-Job -ScriptBlock {
            cd $env:GITHUB_WORKSPACE
            node server.js
          }

          $playitJob = Start-Job -ScriptBlock {
            & "$env:USERPROFILE\playit.exe" --secret $env:PLAYIT_AUTH_KEY
          }

          # Wait for both jobs to complete
          Wait-Job -Job $nodeJob, $playitJob

          # Retrieve job outputs (optional)
          Receive-Job -Job $nodeJob
          Receive-Job -Job $playitJob
